# Generated by Django 3.2.7 on 2021-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('photo', models.ImageField(upload_to='product-photos/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('size', models.PositiveSmallIntegerField(choices=[(30, 30), (35, 35), (40, 40)], default=30, verbose_name='Размер')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('watch_type', models.CharField(choices=[('QE', 'Кварцевые изделия'), ('AE', 'Автоматические изделия')], default='QE', max_length=30, verbose_name='Тип')),
                ('details', models.TextField(verbose_name='Подробности')),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Часы',
            },
        ),
    ]
