# Generated by Django 3.2.7 on 2021-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('photo', models.ImageField(upload_to='product-photos/', verbose_name='Картинка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('length', models.PositiveSmallIntegerField(choices=[(30, 30), (50, 50), (70, 70)], default=30, verbose_name='Длина')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('type_metal', models.CharField(choices=[('silver', 'Серебро'), ('gold', 'Золото')], default='silver', max_length=30, verbose_name='Тип металла')),
                ('assay', models.PositiveSmallIntegerField(verbose_name='Проба металла')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('details', models.TextField(verbose_name='Подробности')),
            ],
            options={
                'verbose_name': 'Цепочка',
                'verbose_name_plural': 'Цепочки',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='watches',
            options={'ordering': ['id'], 'verbose_name': 'Часы', 'verbose_name_plural': 'Часы'},
        ),
        migrations.AlterField(
            model_name='watches',
            name='photo',
            field=models.ImageField(upload_to='product-photos/', verbose_name='Картинка'),
        ),
    ]
