# Generated by Django 3.2.6 on 2021-10-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210925_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
            ],
        ),
        migrations.AddField(
            model_name='chains',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.comments', verbose_name='Коментарии'),
        ),
        migrations.AddField(
            model_name='watches',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.comments', verbose_name='Коментарии'),
        ),
    ]
