# Generated by Django 3.2.7 on 2021-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='avatar',
            field=models.ImageField(null=True, upload_to='customer_avatars', verbose_name='Аватар пользователя'),
        ),
        migrations.AddField(
            model_name='customers',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Узбекский сум'), ('USD', 'Американский доллар'), ('RUB', 'Российский рубль')], default='UZS', max_length=255, verbose_name='Валюта'),
        ),
    ]
