# Generated by Django 3.2.7 on 2021-10-27 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time_order',
            field=models.DateField(default=datetime.date(2021, 10, 27), verbose_name='Дата получения заказа'),
        ),
    ]
