# Generated by Django 3.2.7 on 2021-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orders_time_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False, verbose_name='Статус корзины'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='related_cart', to='shop.CartProduct'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_order',
            field=models.DateField(null=True, verbose_name='Дата получения заказа'),
        ),
    ]
